### ISSUE TITLE
Integration of API Server with Flask Server

### ISSUE THREAD

**Issue by MBSA-INFINITY** [edrisranjbar/SelfUp#80]
- In my views and experience as a **Python based Backend Developer**, the functionalities that API's are providing can be directly written in the flask web server itself.
- This would make the codebase a little more compact and easy to understand and this integration would not take much time as well.
- **I would be more than happy if you assign me this task of integration and I assure you that I will try to complete this task ASAP!**

**Comment by edrisranjbar** [comment]
Thanks for contribution, I'd be grateful to have you helping to enhance the project.

**Comment by MBSA-INFINITY** [comment]
Cool then, I will start working on it and raise a PR ASAP! Thanx for the update!

**Comment by MBSA-INFINITY** [comment]
Please have a look at https://github.com/edrisranjbar/SelfUp/pull/81
